services:
  - type: web
    name: line-dify-chatbot
    env: python
    plan: free
    region: oregon
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: DIFY_API_KEY
        sync: false
      - key: DIFY_API_URL
        sync: false
      - key: PORT
        value: 10000
